### ISSUE TITLE
[FEATURE REQUEST] Add command line arguments

### ISSUE THREAD

**Issue by khrj** [shreyas1307/hackintosh-pkg-cli#7]
It would be nice to add command line arguments, so the script could be run non-interactively

**Comment by shreyas1307** [comment]
Hi, you'll need to be more specific about your feature request.

**Comment by khrj** [comment]
> Hi, you'll need to be more specific about your feature request.

For e.g.

```bash
hackintosh-pkg-cli --add OpenCorePkg Lilu WhateverGreen
```

And then the script doesn't prompt the user to do anything, it just uses whatever arguments are provided
